[tool.poetry]
name = "graph-generator"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.5"
kafka-python-ng = "^2.2.2"
pika = "^1.3.2"
networkx = "^3.3"
matplotlib = "^3.8.4"
numpy = "^1.26.4"
redisgraph = "^2.4.4"
findspark = "^2.0.1"
tqdm = "^4.66.4"
boto3 = "^1.34.101"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
